apiVersion: v1
kind: Service
metadata:
  name: projectname-web
  namespace: projectname-staging
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: projectname-web
